version: 0.0
os: linux

files:             
  - source: ./
    destination: /home/ubuntu/webapp

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - file
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - directory

hooks:
  BeforeInstall:
   - location: ./codedeploy/application_stop.sh
     timeout: 300
     runas: ubuntu
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: ./codedeploy/application_start.sh
     timeout: 300
     runas: ubuntu