version: 0.0
os: linux

files:             
  - source: ./
    destination: /home/ubuntu/webapp

hooks:
  BeforeInstall:
   - location: ./codedeploy/application_stop.sh
     timeout: 300
     runas: ubuntu
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: ./codedeploy/application_start.sh
     timeout: 300
     runas: ubuntu